### ISSUE TITLE
Can not installed. :(

### ISSUE THREAD

**Issue by Ridesa** [jneilliii/OctoPrint-GoogleDriveBackup#1]
Installiere Plugin von hochgeladenem Archiv...
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install file:///tmp/tmpifWJFL.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpifWJFL.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from Google-Drive-Backup==0.0.2) (1.4.2)
Collecting PyDrive2
Downloading https://www.piwheels.org/simple/pydrive2/PyDrive2-1.6.2-py2.py3-none-any.whl
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.0.0)
Requirement already satisfied: psutil<6,>=5.7 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (5.7.2)
Requirement already satisfied: emoji<1,>=0.5.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.5.4)
Requirement already satisfied: monotonic<2,>=1.5; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.5)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.0.7)
Requirement already satisfied: PyYAML<6,>=5.3.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (5.3.1)
Requirement already satisfied: netifaces<1,>=0.10.9 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.10.9)
Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.18.2)
Requirement already satisfied: feedparser<6,>=5.2.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (5.2.1)
Requirement already satisfied: netaddr<1,>=0.7.19 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.7.19)
Requirement already satisfied: requests<3,>=2.23.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (2.24.0)
Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (7.1.2)
Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.4)
Requirement already satisfied: watchdog<1,>=0.10.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.10.3)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.1.0)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.5.0.1)
Requirement already satisfied: Jinja2<3,>=2.11.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (2.11.2)
Requirement already satisfied: frozendict<2,>=1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.2)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.5.0)
Requirement already satisfied: flask<2,>=1.1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.1.2)
Requirement already satisfied: rsa==4.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (4.0)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (2.8.5)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.4.21)
Requirement already satisfied: OctoPrint-FileCheck>=2020.07.06 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (2020.8.7)
Requirement already satisfied: futures<4,>=3.3; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (3.3.0)
Requirement already satisfied: websocket-client<1,>=0.57 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.57.0)
Requirement already satisfied: scandir<2,>=1.10; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.10.0)
Requirement already satisfied: tornado==5.1.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (5.1.1)
Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (3.4)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.1.1)
Requirement already satisfied: markdown<3.2,>=3.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (3.1.1)
Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (2019.8.19)
Requirement already satisfied: chainmap<2,>=1.0.3; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.0.3)
Requirement already satisfied: typing<4,>=3.7.4.1; python_version < "3" in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (3.7.4.1)
Requirement already satisfied: sarge==0.1.5post0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.1.5.post0)
Requirement already satisfied: sentry-sdk<1,>=0.15.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.16.3)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2020.06.22 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (2020.6.22)
Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.2.0)
Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.0.1)
Requirement already satisfied: wrapt<2,>=1.12.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (1.12.1)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (2.0)
Requirement already satisfied: cachelib<1,>=0.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Google-Drive-Backup==0.0.2) (0.1)
Collecting google-api-python-client>=1.12.1
Downloading https://files.pythonhosted.org/packages/fb/79/9ed039a377bd3daf217925d4be4e7f98f79daead843ff5942d6fe780da62/google_api_python_client-1.12.1-py2.py3-none-any.whl (61kB)
Collecting six>=1.13.0
Downloading https://www.piwheels.org/simple/six/six-1.15.0-py2.py3-none-any.whl
Collecting pyOpenSSL>=19.1.0
Downloading https://www.piwheels.org/simple/pyopenssl/pyOpenSSL-19.1.0-py2.py3-none-any.whl (53kB)
Collecting oauth2client>=4.0.0
Downloading https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl (98kB)
Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->Google-Drive-Backup==0.0.2) (2.7.0)
Requirement already satisfied: pytz in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->Google-Drive-Backup==0.0.2) (2019.3)
Requirement already satisfied: idna<3,>=2.5 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Google-Drive-Backup==0.0.2) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Google-Drive-Backup==0.0.2) (1.25.6)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Google-Drive-Backup==0.0.2) (2019.9.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.23.0->OctoPrint->Google-Drive-Backup==0.0.2) (3.0.4)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python2.7/site-packages (from watchdog<1,>=0.10.2->OctoPrint->Google-Drive-Backup==0.0.2) (0.1.2)
Requirement already satisfied: pyasn1>=0.1.3 in /home/pi/oprint/lib/python2.7/site-packages (from rsa==4.0->OctoPrint->Google-Drive-Backup==0.0.2) (0.4.7)
Requirement already satisfied: backports-abc>=0.4 in /home/pi/oprint/lib/python2.7/site-packages (from tornado==5.1.1->OctoPrint->Google-Drive-Backup==0.0.2) (0.5)
Requirement already satisfied: singledispatch in /home/pi/oprint/lib/python2.7/site-packages (from tornado==5.1.1->OctoPrint->Google-Drive-Backup==0.0.2) (3.4.0.3)
Requirement already satisfied: setuptools>=36 in /home/pi/oprint/lib/python2.7/site-packages (from markdown<3.2,>=3.1->OctoPrint->Google-Drive-Backup==0.0.2) (41.5.1)
Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->Google-Drive-Backup==0.0.2) (2.0)
Collecting httplib2<1dev,>=0.9.2
Downloading https://files.pythonhosted.org/packages/98/3f/0769a851fbb0ecc458260055da67d550d3015ebe6b8b861c79ad00147bb9/httplib2-0.18.1.tar.gz (262kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /home/pi/oprint/bin/python2 /home/pi/oprint/local/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-b0jIQZ/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- 'setuptools >= 40.8.0' wheel
cwd: None
Complete output (24 lines):
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/pi/oprint/lib/python2.7/site-packages/pip/__main__.py", line 16, in <module>
from pip._internal.main import main as _main  # isort:skip # noqa
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_internal/main.py", line 13, in <module>
from pip._internal.cli.autocompletion import autocomplete
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 11, in <module>
from pip._internal.cli.main_parser import create_main_parser
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
from pip._internal.cli import cmdoptions
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
from pip._internal.locations import USER_CACHE_DIR, get_src_prefix
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_internal/locations.py", line 18, in <module>
from pip._internal.utils import appdirs
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_internal/utils/appdirs.py", line 16, in <module>
from pip._internal.utils.compat import WINDOWS, expanduser
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_internal/utils/compat.py", line 17, in <module>
from pip._vendor.urllib3.util import IS_PYOPENSSL
File "/home/pi/oprint/lib/python2.7/site-packages/pip/_vendor/urllib3/__init__.py", line 21, in <module>
from logging import NullHandler
ImportError: cannot import name NullHandler
----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/oprint/bin/python2 /home/pi/oprint/local/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-b0jIQZ/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- 'setuptools >= 40.8.0' wheel Check the logs for full command output.
Fehler!
Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by jneilliii** [comment]
This plugin only works in OctoPrint 1.5.0, are you using that version?

**Comment by Ridesa** [comment]
uff sry i have Version 1.4.2. I'll update it and let you know

**Comment by Elmardus** [comment]
Is Octoprint 1.5.0 not yet released? I looked at the Octoprint repo and googled, but couldn't find anything about version 1.5.0.

**Comment by jneilliii** [comment]
It is not released yet, still being actively developed.

**Comment by krudoy** [comment]
> It is not released yet, still being actively developed.

How to update to v 1.5?
Changed OctoPrint Release Channel to Devel RCs. but still don't see 1.5 available...

**Comment by jneilliii** [comment]
I think the only way to do this is to install using the pip command in SSH. Otherwise, the versioning isn't detected properly using the git commit tracking and such. Assuming you're running an octopi image this is the command that you would run. This will restart OctoPrint so make sure you're not printing while doing it.

```
~/oprint/bin/pip install --upgrade --no-cache-dir https://github.com/OctoPrint/OctoPrint/archive/maintenance.zip
sudo service octoprint restart
```

**Comment by krudoy** [comment]
ERROR: After October 2020 you may experience errors when installing or
updating packages. This is because pip will change the way that it resolves
dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with
the new resolver before it becomes the default.

thespaghettidetective 1.4.2 requires OctoPrint>=1.3.8, but you'll have
octoprint 0+unknown which is incompatible.
Successfully installed OctoPrint-0+unknown ifaddr-0.1.7 zeroconf-0.24.5

**Comment by jneilliii** [comment]
> octoprint 0+unknown which is incompatible.

yeah, I was afraid of that. since it's not officially released the info isn't there for it to flag the version properly. It works on local checkouts of the git repository but I guess not on installs. I apologize for leading you down the wrong path. If you want to go back you can just run this command I believe and it will go back to the official 1.4.2 release.

```
~/oprint/bin/pip install --force reinstall OctoPrint
```

**Comment by jneilliii** [comment]
correction...
```
~/oprint/bin/pip install --force-reinstall OctoPrint
```

**Comment by krudoy** [comment]
Thanks :)

What is so special in 1.5, which makes the plugin require that version?
Really want to have the ability to upload backups automatically into the
cloud.

**Comment by jneilliii** [comment]
It's the first version that has the necessary event hook that is being used to initialize the upload. Older versions don't have that event hook.
